import { useParams } from "react-router-dom";

function ValidationPage() {
  //const { code } = useParams();

  const permit = {
    code : "8DEB11A545EE76E",
    description:
      "BUSINESS PERMIT BILL FOR YEAR- 2026, OWNER :",
    documentDate: new Date().toLocaleString(),
    generatedBy: "REHEMA OMAR",
    amount: "1000000.00",
    issuedTo:
      "BUSINESS PERMIT BILL FOR YEAR- 2026, OWNER :",
    subCounty: "",
    ward: "",
    zone: "",
  };

  const rows = [
    ["Code", permit.code],
    ["Description", permit.description],
    ["Document Date", permit.documentDate],
    ["Generated by", permit.generatedBy],
    ["Amount", permit.amount],
    ["Issued To", permit.issuedTo],
    ["Sub County", permit.subCounty],
    ["Ward", permit.ward],
    ["Zone", permit.zone],
  ];

  return (
    <div className="min-h-screen bg-gray-100 flex justify-center py-8">
      <div className="bg-white w-full max-w-lg shadow-lg border border-gray-300">

        <div className="p-8 text-center">
          <h1 className="text-5xl font-bold text-gray-800">
            QR Code Validation
          </h1>
        </div>

        <div className="py-10 text-center">
          <h2 className="text-6xl font-extrabold text-green-600">
            VALID
          </h2>
        </div>

        <table className="w-full border-collapse">
          <thead>
            <tr>
              <th className="border bg-gray-100 p-3 text-left">
                Attribute
              </th>

              <th className="border bg-gray-100 p-3 text-left">
                Value/Details
              </th>
            </tr>
          </thead>

          <tbody>
            {rows.map(([label, value]) => (
              <tr key={label}>
                <td className="border p-3 font-bold text-gray-700">
                  {label}
                </td>

                <td className="border p-3 text-sky-500">
                  {value}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

      </div>
    </div>
  );
}

export default ValidationPage;